### ISSUE TITLE
basic example seems to be missing config-map

### ISSUE THREAD

**Issue by medyagh** [amimof/multikube#29]
following https://github.com/amimof/multikube/blob/master/docs/examples/kubernetes-example.md

```
kubectl create namespace multikube
kubectl create secret generic kubeconfig --from-file ~/.kube/config -n multikube
kubectl create namespace multikube
kubectl apply -f https://raw.githubusercontent.com/amimof/multikube/master/deploy/k8s.yaml
```
describe pod:
```
 Warning  FailedMount  23s (x7 over 55s)  kubelet, minikube  MountVolume.SetUp failed for volume "multikube-kubeconfig" : configmap "multikube-kubeconfig" not found
```

**Comment by amimof** [comment]
Hi, thank you for your input :) I see that the configmap is referenced by wrong name. See https://github.com/amimof/multikube/blob/master/deploy/k8s.yaml#L57

Will update asap

**Comment by amimof** [comment]
@medyagh #30 fixes this issue. Please let me know if you run into problems. Cheers!
